### ISSUE TITLE
create git tag for first release

### ISSUE THREAD

**Issue by guruofquality** [pothosware/SoapyRedPitaya#4]
@pavel-demin How do you feel about SoapyRedPitaya being ready for a release tag? Any preference for the version number? year.month, major.minor? I am looking to upload to the drivers ppa once there is tag: https://launchpad.net/~myriadrf/+archive/ubuntu/drivers/+packages

**Comment by pavel-demin** [comment]
Is it OK to make a release with one known bug https://github.com/pothosware/SoapyRedPitaya/issues/3?

I don't have any preference for the version number. The format used for other Soapy\* drivers is OK for me.

**Comment by guruofquality** [comment]
> Is it OK to make a release with one known bug #3?

Its not really breaking, but I think there is something minor we can do. Let me double check a few things...

> I don't have any preference for the version number. The format used for other Soapy\* drivers is OK for me.

Cool. Will do

**Comment by guruofquality** [comment]
Done.
